apiVersion: v2
dependencies:
- condition: keycloak.enabled
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 16.1.7
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
description: Identity Helm Chart for Kubernetes
icon: https://helm.camunda.io/imgs/camunda.svg
name: identity
type: application
version: 8.3.5
