global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    tag:

console:
  # Camunda Enterprise repository.
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.6.55

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.6.8

operate:
  # https://hub.docker.com/r/camunda/operate/tags
  image:
    repository: camunda/operate
    tag: 8.6.9

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.6.5

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags
  image:
    repository: camunda/tasklist
    tag: 8.6.9

webModeler:
  enabled: true
  # https://hub.docker.com/r/camunda/web-modeler-restapi
  image:
    # renovate: datasource=docker depName=camunda/web-modeler-restapi
    tag: 8.6.7
  restapi:
    mail:
      smtpHost: "smtp"
      smtpPort: 587
      ## @param webModeler.restapi.mail.smtpUser can be used to provide a user for the SMTP server
      smtpUser: ""
      ## @param webModeler.restapi.mail.smtpPassword can be used to provide a password for the SMTP server; ignored if `webModeler.restapi.mail.existingSecret` is set
      smtpPassword: ""
      ## @param webModeler.restapi.mail.smtpTlsEnabled if true, enforces TLS encryption for SMTP connections (using STARTTLS)
      smtpTlsEnabled: true
      ## @param webModeler.restapi.mail.existingSecret can be used to provide the name of an existing secret resource containing the SMTP password
      existingSecret:
      ## @param webModeler.restapi.mail.existingSecretPasswordKey can be used to provide the name of an existing secret key containing the SMTP password
      existingSecretPasswordKey: "smtp-password"
      ## @param webModeler.restapi.mail.fromAddress defines the email address that will be displayed as the sender of emails sent by WebModeler
      # NOTE: This value is mandatory.
      fromAddress: "camunda"
      ## @param webModeler.restapi.mail.fromName defines the name that will be displayed as the sender of emails sent by WebModeler
      fromName: "Camunda 8"

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.6.9

zeebeGateway:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.6.9

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.6.8

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  image:
    repository: bitnami/keycloak
    tag: 25.0.6
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnami/postgresql
      tag: 15.10.0-debian-12-r2

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.15.4
  master:
    ## @param elasticsearch.master.replicaCount defines number of master-elegible replicas to deploy
    replicaCount: 3
    ## @param elasticsearch.master.podAntiAffinityPreset defines Pod anti-affinity preset. Ignored if master.affinity is set
    podAntiAffinityPreset: hard
    containerSecurityContext:
    ## @param elasticsearch.master.containerSecurityContext.readOnlyRootFilesystem
      readOnlyRootFilesystem: true
    ## @param elasticsearch.master.masterOnly
    masterOnly: false
    ## @param elasticsearch.master.heapSize
    heapSize: 1024m
    persistence:
      ## @param elasticsearch.master.persistence.size
      size: 64Gi

prometheusServiceMonitor:
  ## @param prometheusServiceMonitor.enabled if true then a service monitor will be deployed, which allows an installed prometheus controller to scrape metrics from the deployed pods
  enabled: true
  ## @extra promotheuServiceMonitor.labels can be set to configure extra labels, which will be added to the servicemonitor and can be used on the prometheus controller for selecting the servicemonitors
  labels:
  ## @param prometheusServiceMonitor.labels.release
    release: obs-stack